---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ZhaoKai.
--- DateTime: 2023/11/14 10:47
---
local do_plugin_setup = function()
    -- 启动页配制
    require("plugin-config/dashboard")
    -- 文件及文件夹配置
    require("plugin-config/telescope")
    require("plugin-config/filebrowser")
    -- 主题配置
    --require("plugin-config/gruvbox")
    require("plugin-config/kanagawa")
    -- 标签栏
    require("plugin-config/bufferline")
    -- 侧边栏
    require("plugin-config/nvimtree")
    --底部状态栏
    require("plugin-config/lualine")
    --快速跳转
    require("plugin-config/leap")
    require("plugin-config/flit")
    --markdown
    require("plugin-config/markdown")
    --引导线
    require("plugin-config/indent_blankline")
    --目录栏
    require("plugin-config/vista")
    --快捷键
    require("plugin-config/whichkey")
end

do_plugin_setup()
