---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ZhaoKai.
--- DateTime: 2023/3/9 13:58
---
local opts = {
    cmd = {
        "marksman", "server"
    },
    filetypes = {
        "markdown"
    },
    flags = {
        debounce_text_changes = 150,
    },
    single_file_support={
        true
    },
    on_attach = function(bufnr)
        local function buf_set_keymap(...)
            vim.api.nvim_buf_set_keymap(bufnr, ...)
        end
        -- 绑定快捷键
        require("keybindings").mapLSP(buf_set_keymap)
        -- 保存时自动格式化
        vim.cmd("autocmd BufWritePre <buffer> AutoFormat()<CR>")
    end,
}

return opts