vim.api.nvim_set_keymap( "i", ",f", "<Esc>/<++><CR>:nohlsearch<CR>\"_c4l", { noremap = true, silent = true })
vim.api.nvim_set_keymap( "i", ",w", "<Esc>/ <++><CR>:nohlsearch<CR>\"_c5l<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap( "i", ",n", "---<Enter><Enter>", { noremap = true, silent = true })
vim.api.nvim_set_keymap( "i", ",b", "**** <++><Esc>F*hi", { noremap = true, silent = true })
vim.api.nvim_set_keymap( "i", ",s", "~~~~ <++><Esc>F~hi", { noremap = true, silent = true })
vim.api.nvim_set_keymap( "i", ",i", "** <++><Esc>F*i", { noremap = true, silent = true })
vim.api.nvim_set_keymap( "i", ",d", "`` <++><Esc>F`i", { noremap = true, silent = true })
vim.api.nvim_set_keymap( "i", ",c", "```<Enter><++><Enter>```<Enter><Enter><++><Esc>4kA", { noremap = true, silent = true })
vim.api.nvim_set_keymap( "i", ",m", "- [ ]", { noremap = true, silent = true })
vim.api.nvim_set_keymap( "i", ",p", "![](<++>) <++><Esc>F[a", { noremap = true, silent = true })
vim.api.nvim_set_keymap( "i", ",a", "[](<++>) <++><Esc>F[a", { noremap = true, silent = true })
vim.api.nvim_set_keymap( "i", ",1", "#<Space><Enter><++><Esc>kA", { noremap = true, silent = true })
vim.api.nvim_set_keymap( "i", ",2", "##<Space><Enter><++><Esc>kA", { noremap = true, silent = true })
vim.api.nvim_set_keymap( "i", ",3", "###<Space><Enter><++><Esc>kA", { noremap = true, silent = true })
vim.api.nvim_set_keymap( "i", ",4", "####<Space><Enter><++><Esc>kA", { noremap = true, silent = true })
vim.api.nvim_set_keymap( "i", ",l", "--------<Enter>", { noremap = true, silent = true })